/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GovernmentSecretaryRole;

import Business.Enterprise.Enterprise;
import Business.Org.Organization;
import Business.Org.OrgSecretary;
import Business.SystemUserAccount.SystemUsers;
import Business.WorkQueue.GovFundReq;
import Business.WorkQueue.WorkReq;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Pratik
 */
public class SecretaryWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SecretaryWorkAreaJPanel
     */
    private JPanel jPanel;
    private SystemUsers usrAcnt;
    private OrgSecretary secOrg;
    private Enterprise entrpz;

    public SecretaryWorkAreaJPanel(JPanel jpanel, SystemUsers userAccount, Organization organization, Enterprise enterprise) {
        initComponents();
        this.entrpz = enterprise;
        this.jPanel = jpanel;
        this.secOrg = (OrgSecretary) organization;
        this.usrAcnt = userAccount;

        ppltTbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblWrkReqTbl = new javax.swing.JTable();
        btnAssgnToMe = new javax.swing.JButton();
        btnProcess = new javax.swing.JButton();
        lblSecWrkArea = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setForeground(new java.awt.Color(255, 255, 255));
        setToolTipText("");

        tblWrkReqTbl.setBackground(new java.awt.Color(204, 204, 204));
        tblWrkReqTbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tblWrkReqTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Location", "Sender", "Receiver", "Status", "Amount", "Message"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWrkReqTbl);

        btnAssgnToMe.setBackground(new java.awt.Color(0, 102, 102));
        btnAssgnToMe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAssgnToMe.setText("Assign To Me");
        btnAssgnToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssgnToMeActionPerformed(evt);
            }
        });

        btnProcess.setBackground(new java.awt.Color(0, 102, 102));
        btnProcess.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnProcess.setText("Process Request");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        lblSecWrkArea.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSecWrkArea.setText("Secretary Work Area");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Secratary.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(lblSecWrkArea, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(btnAssgnToMe)
                        .addGap(38, 38, 38)
                        .addComponent(btnProcess))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel2)))
                .addContainerGap(534, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblSecWrkArea, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssgnToMe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssgnToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssgnToMeActionPerformed
        int selectedRow = tblWrkReqTbl.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first from the table to view details");
            return;
        } else {
            WorkReq req = (GovFundReq) tblWrkReqTbl.getValueAt(selectedRow, 0);
            if (req.getReqStatus().equals("Sent to Secretary")) {
                req.setRcvr(usrAcnt);
                req.setReqStatus("Pending on " + req.getRcvr().getEmploye().getEmpName());
                ppltTbl();
                JOptionPane.showMessageDialog(null, "Success !! Request is assigned to you ");
            } else {
                JOptionPane.showMessageDialog(null, "Can't assign this work request, as the work request is in " + req.getReqStatus() + " status", "Warning!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAssgnToMeActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblWrkReqTbl.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first from the table to view details");
            return;
        } else {
            GovFundReq fundReq = (GovFundReq) tblWrkReqTbl.getValueAt(selectedRow, 0);
            if (fundReq.getReqStatus().equals("Rejected")) {
                JOptionPane.showMessageDialog(null, "Cannot process a Rejected Request", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            if (fundReq.getReqStatus().equalsIgnoreCase("Sent to Treasurer")) {
                JOptionPane.showMessageDialog(null, "Request already processed" , "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (fundReq.getReqStatus().equalsIgnoreCase("Sent to Secretary")) {
                JOptionPane.showMessageDialog(null, "Please assign selected request first");
                return;
            }
             if(!usrAcnt.equals(fundReq.getRcvr())){
             JOptionPane.showMessageDialog(null, "Not Authorized", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (!usrAcnt.getEmploye().equals(fundReq.getRcvr().getEmploye())) {
                JOptionPane.showMessageDialog(null, "Request assigned to other Officer", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            
            SecretaryProcessWorkRequestJPanel secPrcWrkreqJPanel = new SecretaryProcessWorkRequestJPanel(jPanel, usrAcnt, fundReq, entrpz);
            jPanel.add("secretaryProcessWorkRequestJPanel", secPrcWrkreqJPanel);
            CardLayout layout = (CardLayout) jPanel.getLayout();
            layout.next(jPanel);

        }
    }//GEN-LAST:event_btnProcessActionPerformed

    public void ppltTbl() {
        DefaultTableModel model = (DefaultTableModel) tblWrkReqTbl.getModel();

        model.setRowCount(0);

        for (WorkReq req : secOrg.getWrkQ().getWrkReqs()) {
            String status = req.getReqStatus();
            Object[] row = new Object[6];
            row[0] = ((GovFundReq) req);
            row[1] = req.getSndr().getEmploye().getEmpName();
            if (status.equalsIgnoreCase("Sent to Treasurer") || status.equalsIgnoreCase("Sent to Secretary")) {
                row[2] = null;
            } else {
                row[2] = req.getRcvr() == null ? null : req.getRcvr().getEmploye().getEmpName();
            }
            row[3] = status;
            row[4] = ((GovFundReq) req).getAmountRequested();
            row[5] = ((GovFundReq) req).getWrkMsg();

            model.addRow(row);
        }
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblWrkReqTbl.setRowSorter(sorter);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssgnToMe;
    private javax.swing.JButton btnProcess;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSecWrkArea;
    private javax.swing.JTable tblWrkReqTbl;
    // End of variables declaration//GEN-END:variables
}
