/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGOAdministratorRole;

import userinterface.HealthcareOfficerRole.*;
import userinterface.NGOAdministratorRole.NGOAdministratorWorkAreaPanel;
import Business.Enterprise.Enterprise;
import Business.Org.OrgNGODirector;
import Business.Org.Organization;
import Business.Org.OrgSecretary;
import Business.SystemUserAccount.SystemUsers;
import Business.WorkQueue.GovFundReq;
import Business.WorkQueue.NGOFundRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Parth
 */
public class NGOAdministratorProcessWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    private JPanel jPnl;
    private Enterprise ent;
    private SystemUsers usrAcc;
    private NGOFundRequest ngoFndReq;
    private OfficerWorkAreaJPanel offrWrkAreaJPnl;

    public NGOAdministratorProcessWorkRequestJPanel(JPanel jPanel, SystemUsers userAccount, NGOFundRequest fundRequest, Enterprise enterprise) {
        initComponents();

        this.jPnl = jPanel;
        this.ent = enterprise;
        this.usrAcc = userAccount;
        this.ngoFndReq = fundRequest;
        txtAmtNdd.setText(String.valueOf(ngoFndReq.getAmountRequired()));
        txtHospNm.setText(ngoFndReq.getNameOfHospital());
        txtHospAddr.setText(String.valueOf(ngoFndReq.getAddressOfHospital()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAmtNdd = new javax.swing.JTextField();
        lblAmtNdd = new javax.swing.JLabel();
        lblMsg = new javax.swing.JLabel();
        txtMsg = new javax.swing.JTextField();
        lblNgoAdmReqPrcs = new javax.swing.JLabel();
        btnSndToDrctrApprvl = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblHospNm = new javax.swing.JLabel();
        txtHospNm = new javax.swing.JTextField();
        txtHospAddr = new javax.swing.JTextField();
        lblHospAddr = new javax.swing.JLabel();
        btnReq = new javax.swing.JButton();
        img = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));

        txtAmtNdd.setEnabled(false);

        lblAmtNdd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblAmtNdd.setText("Amount Needed:");

        lblMsg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMsg.setText("Message:");

        lblNgoAdmReqPrcs.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblNgoAdmReqPrcs.setText("NGO Admin Request Process work Area ");

        btnSndToDrctrApprvl.setBackground(new java.awt.Color(0, 102, 102));
        btnSndToDrctrApprvl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSndToDrctrApprvl.setText("Send to Director for approval");
        btnSndToDrctrApprvl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSndToDrctrApprvlActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblHospNm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblHospNm.setText("Hospital Name:");

        txtHospNm.setEnabled(false);

        txtHospAddr.setEnabled(false);

        lblHospAddr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblHospAddr.setText("Hospital Address:");

        btnReq.setBackground(new java.awt.Color(0, 102, 102));
        btnReq.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnReq.setText("Reject");
        btnReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqActionPerformed(evt);
            }
        });

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NGO.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNgoAdmReqPrcs)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblAmtNdd, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblHospNm, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(38, 38, 38)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtAmtNdd, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtHospNm, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblMsg)
                                                    .addComponent(lblHospAddr))
                                                .addGap(38, 38, 38)
                                                .addComponent(txtHospAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSndToDrctrApprvl)
                                        .addGap(39, 39, 39)
                                        .addComponent(btnReq, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(lblNgoAdmReqPrcs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHospNm)
                            .addComponent(txtHospNm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAmtNdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAmtNdd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHospAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHospAddr))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMsg))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSndToDrctrApprvl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReq, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        jPnl.remove(this);
        Component[] componentArray = jPnl.getComponents();
        Component component = componentArray[componentArray.length - 1];
        NGOAdministratorWorkAreaPanel ngoAdministratorWorkAreaJPanel = (NGOAdministratorWorkAreaPanel) component;
        ngoAdministratorWorkAreaJPanel.populateRequestTable();
        CardLayout layout = (CardLayout) jPnl.getLayout();
        layout.previous(jPnl);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSndToDrctrApprvlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSndToDrctrApprvlActionPerformed
        // TODO add your handling code here:

        String message = txtMsg.getText();
        if (message.equals("")) {
            JOptionPane.showMessageDialog(null, "Message is mandatory!");
            return;
        } else {
            ngoFndReq.setWrkMsg(message);

            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");

            if (dialogResult == JOptionPane.YES_OPTION) {

                ngoFndReq.setSndr(usrAcc);
                ngoFndReq.setReqStatus("Sent to Director");

                Organization org = null;
                for (Organization organization : ent.getOrgDir().getOrganizations()) {
                    if (organization instanceof OrgNGODirector) {
                        org = organization;
                        break;
                    }
                }
                if (org != null) {
                    org.getWrkQ().getWrkReqs().add(ngoFndReq);
                    usrAcc.getWorkQ().getWrkReqs().add(ngoFndReq);
                }
                JOptionPane.showMessageDialog(null, "Request to Director Successful!!!");
                txtMsg.setText("");
                btnReq.setEnabled(false);
                btnSndToDrctrApprvl.setEnabled(false);
            }
            txtMsg.setText("");
        }

    }//GEN-LAST:event_btnSndToDrctrApprvlActionPerformed

    private void btnReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqActionPerformed
        String message = txtMsg.getText();
        if (message.equals("")) {
            JOptionPane.showMessageDialog(null, "Message is mandatory!");
            return;
        } else {
            ngoFndReq.setWrkMsg(message);
            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");

            if (dialogResult == JOptionPane.YES_OPTION) {
                ngoFndReq.setReqStatus("Rejected");
                txtMsg.setText("");
                btnReq.setEnabled(false);
                btnSndToDrctrApprvl.setEnabled(false);
            }

            txtMsg.setText("");
        }
    }//GEN-LAST:event_btnReqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReq;
    private javax.swing.JButton btnSndToDrctrApprvl;
    private javax.swing.JLabel img;
    private javax.swing.JLabel lblAmtNdd;
    private javax.swing.JLabel lblHospAddr;
    private javax.swing.JLabel lblHospNm;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblNgoAdmReqPrcs;
    private javax.swing.JTextField txtAmtNdd;
    private javax.swing.JTextField txtHospAddr;
    private javax.swing.JTextField txtHospNm;
    private javax.swing.JTextField txtMsg;
    // End of variables declaration//GEN-END:variables
}
