/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.NGOAdministratorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Networks.Networks;
import Business.Org.OrgNGOAdmin;
import Business.Org.Organization;
import Business.SystemUserAccount.SystemUsers;
import Business.WorkQueue.GovFundReq;
import Business.WorkQueue.NgoDonorReq;
import Business.WorkQueue.NGOFundRequest;
import Business.WorkQueue.WorkReq;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import userinterface.HealthcareOfficerRole.MapJPanel;
import userinterface.HealthcareOfficerRole.OfficerProcessWorkRequestJPanel;

/**
 *
 * @author Parth
 */
public class NGOAdministratorWorkAreaPanel extends javax.swing.JPanel {

    private JPanel usrCnter;
    private SystemUsers usrAcc;
    private EcoSystem ecoSys;
    private Enterprise ent;
    private OrgNGOAdmin ngoAdmOrg;

    /**
     * Creates new form NGOAdministratorWorkAreaPanel
     */
    public NGOAdministratorWorkAreaPanel(JPanel userProcessContainer, SystemUsers userAccount, Organization organization, Enterprise enterprise) {
        initComponents();
        this.usrCnter = userProcessContainer;
        this.ngoAdmOrg = (OrgNGOAdmin) organization;
        this.usrAcc = userAccount;
        this.ent = enterprise;
        populateRequestTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNgoAdmWrkArea = new javax.swing.JTable();
        btnAssigndToMe = new javax.swing.JButton();
        btnPrcsReq = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        mapBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        img = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));

        tblNgoAdmWrkArea.setBackground(new java.awt.Color(204, 204, 204));
        tblNgoAdmWrkArea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Location", "Sender", "Receiver", "Status", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNgoAdmWrkArea);

        btnAssigndToMe.setBackground(new java.awt.Color(0, 102, 102));
        btnAssigndToMe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAssigndToMe.setText("Assign To Me");
        btnAssigndToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssigndToMeActionPerformed(evt);
            }
        });

        btnPrcsReq.setBackground(new java.awt.Color(0, 102, 102));
        btnPrcsReq.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPrcsReq.setText("Process Request");
        btnPrcsReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrcsReqActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NGO Admin Panel");

        mapBtn.setBackground(new java.awt.Color(0, 102, 102));
        mapBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mapBtn.setText("Verification on Map");
        mapBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapBtnActionPerformed(evt);
            }
        });

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/OfficeProcess.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(363, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAssigndToMe, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrcsReq)
                        .addGap(400, 400, 400))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mapBtn)
                        .addGap(461, 461, 461))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(274, 274, 274))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrcsReq, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAssigndToMe, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(mapBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssigndToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssigndToMeActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblNgoAdmWrkArea.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first from the table to view details");
            return;
        } else {
            WorkReq request = (NGOFundRequest) tblNgoAdmWrkArea.getValueAt(selectedRow, 0);
            if (request.getReqStatus().equals("Sent")) {
                request.setRcvr(usrAcc);
                request.setReqStatus("Pending on " + request.getRcvr().getEmploye().getEmpName());
                populateRequestTable();
                JOptionPane.showMessageDialog(null, "Success !! Request is assigned to you ");
            } else {
                JOptionPane.showMessageDialog(null, "Can't assign this work request, as the work request is in " + request.getReqStatus() + " status", "Warning!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAssigndToMeActionPerformed

    private void btnPrcsReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrcsReqActionPerformed
        
     // TODO add your handling code here:
        int selectedRow = tblNgoAdmWrkArea.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first from the table to view details");
            return;
        } else {

            NGOFundRequest request = (NGOFundRequest) tblNgoAdmWrkArea.getValueAt(selectedRow, 0);

            if (request.getReqStatus().equals("Rejected")) {
                JOptionPane.showMessageDialog(null, "Cannot process a Rejected Request", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (request.getReqStatus().equalsIgnoreCase("Sent to Director")) {
                JOptionPane.showMessageDialog(null, "Request already processed", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (request.getReqStatus().equalsIgnoreCase("Sent")) {
                JOptionPane.showMessageDialog(null, "Assign the request first");
                return;
            }
            if (!usrAcc.equals(request.getRcvr())) {
                JOptionPane.showMessageDialog(null, "Not Authorized", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (!usrAcc.getEmploye().equals(request.getRcvr().getEmploye())) {
                JOptionPane.showMessageDialog(null, "Request assigned to other Officer", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            } else {

                NGOAdministratorProcessWorkRequestJPanel panel = new NGOAdministratorProcessWorkRequestJPanel(usrCnter, usrAcc, request, ent);
                usrCnter.add("OfficerProcessWorkRequestJPanel", panel);
                CardLayout layout = (CardLayout) usrCnter.getLayout();
                layout.next(usrCnter);

            }
    }
    }//GEN-LAST:event_btnPrcsReqActionPerformed

    private void mapBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapBtnActionPerformed
        // TODO add your handling code here:
        MapJPanel mapJPanel = new MapJPanel(usrCnter);
        usrCnter.add("mapJPanel",mapJPanel);
        CardLayout layout=(CardLayout)usrCnter.getLayout();
        layout.next(usrCnter);
    }//GEN-LAST:event_mapBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssigndToMe;
    private javax.swing.JButton btnPrcsReq;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mapBtn;
    private javax.swing.JTable tblNgoAdmWrkArea;
    // End of variables declaration//GEN-END:variables

    void populateRequestTable() {
         DefaultTableModel model = (DefaultTableModel) tblNgoAdmWrkArea.getModel();

        model.setRowCount(0);

        for (WorkReq request : ngoAdmOrg.getWrkQ().getWrkReqs()) {
            Object[] row = new Object[5];
            String status = request.getReqStatus();
            row[0] = ((NGOFundRequest) request);
            row[1] = request.getSndr().getEmploye().getEmpName();
            if (status.equalsIgnoreCase("Sent to Director") ) {
                row[2] = null;
            } else {
                row[2] = request.getRcvr() == null ? null : request.getRcvr().getEmploye().getEmpName();
            }
            row[3] = request.getReqStatus();
            row[4] = ((NGOFundRequest) request).getAmountRequired();

            model.addRow(row);
        }
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblNgoAdmWrkArea.setRowSorter(sorter);
    }
}
