/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InsuranceAgentRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.EntInsurance;
import Business.Insurance.Insurance;
import Business.InsuranceCustomer.InsuranceCustomer;
import Business.SystemUserAccount.SystemUsers;
import java.awt.CardLayout;
import java.awt.Color;

import java.text.SimpleDateFormat;
import java.util.Calendar;

import java.util.List;
import java.util.UUID;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ankitajha
 */

public class AddNewPolicyHolderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewUserJPanel
     */
    private JPanel userProcessContainer;
    private SystemUsers usrAcnt;
    private EntInsurance insrCmnEntr;
    private String plcyNum;

    public AddNewPolicyHolderJPanel(JPanel userProcessContainer, SystemUsers userAccount, Enterprise enterprise, String policyNumber) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.insrCmnEntr = (EntInsurance) enterprise;
        this.usrAcnt = userAccount;
        this.plcyNum = policyNumber;
        populateFields();
        pplTbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddNewCust = new javax.swing.JLabel();
        lblPlcyNo = new javax.swing.JLabel();
        txtPlcyNum = new javax.swing.JTextField();
        lblFrstNm = new javax.swing.JLabel();
        txtFrstNm = new javax.swing.JTextField();
        lblLstNm = new javax.swing.JLabel();
        txtLstNm = new javax.swing.JTextField();
        lblSsn = new javax.swing.JLabel();
        txtSsn = new javax.swing.JTextField();
        lblDtOfBrth = new javax.swing.JLabel();
        txtAddr = new javax.swing.JTextField();
        lblGndr = new javax.swing.JLabel();
        lblAddr = new javax.swing.JLabel();
        lblInsPlcyNm = new javax.swing.JLabel();
        txtInsPlcyNm = new javax.swing.JComboBox();
        btnAddCstmr = new javax.swing.JButton();
        lblPrsnlInfo = new javax.swing.JLabel();
        lblInsInfo = new javax.swing.JLabel();
        lblPhn = new javax.swing.JLabel();
        txtPhn = new javax.swing.JTextField();
        lblInsCvrgPercent = new javax.swing.JLabel();
        txtInsCvrgPercent = new javax.swing.JTextField();
        cbGndr = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNewCstmr = new javax.swing.JTable();
        lblAlCstmr = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        img = new javax.swing.JLabel();
        dobJDateChooser = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(0, 153, 153));

        lblAddNewCust.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblAddNewCust.setForeground(new java.awt.Color(0, 51, 51));
        lblAddNewCust.setText("Enroll Customer");

        lblPlcyNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPlcyNo.setForeground(new java.awt.Color(0, 51, 51));
        lblPlcyNo.setText("Policy Number ");

        lblFrstNm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFrstNm.setForeground(new java.awt.Color(0, 51, 51));
        lblFrstNm.setText("First Name");

        lblLstNm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLstNm.setForeground(new java.awt.Color(0, 51, 51));
        lblLstNm.setText("Last Name");

        lblSsn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSsn.setForeground(new java.awt.Color(0, 51, 51));
        lblSsn.setText("SSN");

        lblDtOfBrth.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDtOfBrth.setForeground(new java.awt.Color(0, 51, 51));
        lblDtOfBrth.setText("Date of birth");

        lblGndr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGndr.setForeground(new java.awt.Color(0, 51, 51));
        lblGndr.setText("Gender");

        lblAddr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAddr.setForeground(new java.awt.Color(0, 51, 51));
        lblAddr.setText("Address");

        lblInsPlcyNm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInsPlcyNm.setForeground(new java.awt.Color(0, 51, 51));
        lblInsPlcyNm.setText("Insurance Policy Name");

        txtInsPlcyNm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInsPlcyNmFocusGained(evt);
            }
        });
        txtInsPlcyNm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsPlcyNmActionPerformed(evt);
            }
        });

        btnAddCstmr.setBackground(new java.awt.Color(0, 102, 102));
        btnAddCstmr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddCstmr.setForeground(java.awt.Color.white);
        btnAddCstmr.setText("Add Customer");
        btnAddCstmr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCstmrActionPerformed(evt);
            }
        });

        lblPrsnlInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPrsnlInfo.setForeground(new java.awt.Color(0, 51, 51));
        lblPrsnlInfo.setText("Personal Information");

        lblInsInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblInsInfo.setForeground(new java.awt.Color(0, 51, 51));
        lblInsInfo.setText("Insurance  Information");

        lblPhn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPhn.setForeground(new java.awt.Color(0, 51, 51));
        lblPhn.setText("Phone");

        lblInsCvrgPercent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInsCvrgPercent.setForeground(new java.awt.Color(0, 51, 51));
        lblInsCvrgPercent.setText("Insurance Coverage %");

        cbGndr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Female", "Male", "Other" }));

        tblNewCstmr.setBackground(new java.awt.Color(204, 204, 204));
        tblNewCstmr.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tblNewCstmr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer Name", "Policy Number", "Policy Name", "Coverage %"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNewCstmr);

        lblAlCstmr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAlCstmr.setForeground(new java.awt.Color(255, 255, 255));
        lblAlCstmr.setText("All Customers");

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/magnify.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDtOfBrth)
                            .addComponent(lblSsn)
                            .addComponent(lblAddr)
                            .addComponent(lblFrstNm))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblGndr)
                                    .addComponent(lblPhn)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPlcyNum, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtFrstNm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtSsn, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(dobJDateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(28, 28, 28)
                                            .addComponent(lblLstNm))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLstNm)
                                    .addComponent(txtPhn)
                                    .addComponent(cbGndr, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(txtAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblPlcyNo))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(lblInsPlcyNm)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtInsPlcyNm, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblInsCvrgPercent)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtInsCvrgPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(btnAddCstmr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 550, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(lblPrsnlInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(114, 114, 114)
                .addComponent(lblAddNewCust)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlCstmr))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(lblInsInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddNewCust))
                .addGap(18, 18, 18)
                .addComponent(lblPrsnlInfo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlcyNum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlcyNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLstNm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFrstNm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFrstNm)
                        .addComponent(lblLstNm)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbGndr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGndr))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(lblDtOfBrth)))
                    .addComponent(dobJDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhn)
                    .addComponent(txtPhn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSsn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddr)
                    .addComponent(txtAddr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInsInfo)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInsPlcyNm)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtInsPlcyNm, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInsCvrgPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInsCvrgPercent))
                .addGap(18, 18, 18)
                .addComponent(btnAddCstmr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lblAlCstmr)
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(373, 373, 373))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCstmrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCstmrActionPerformed

        if (txtFrstNm.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide first name");
            return;
        }

        if (txtLstNm.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide last name");
            return;
        }

        if (dobJDateChooser.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Please provide Date of birth");
            return;
        }

        if (cbGndr.getItemCount() == 0) {
            JOptionPane.showMessageDialog(null, "Please provide Gender");
            return;
        }

        if (cbGndr.getItemCount() == 0) {
            JOptionPane.showMessageDialog(null, "Please provide Gender");
            return;
        }

        if (txtSsn.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide SSN");
            return;
        }

        if (txtPhn.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide phone");
            return;
        }

        if (txtAddr.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide address");
            return;
        }

        if (txtInsCvrgPercent.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide Insurance Coverage");
            return;
        } else {

            String firstName = txtFrstNm.getText().trim();
            String lastName = txtLstNm.getText().trim();
            SimpleDateFormat sdf = new SimpleDateFormat("MM-dd-yyyy");
            String dateOfBirth = "";
            try {
                dateOfBirth = sdf.format(dobJDateChooser.getDate());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Please select customer's dob");
            }
            String gender = cbGndr.getSelectedItem().toString();

            String ssn = txtSsn.getText().trim();
            if (!ssnPatternCheck()) {
                JOptionPane.showMessageDialog(null, "/* United States Social Security numbers are nine-digit numbers in the format AAA-GG-SSSS with following rules. */             \n"
                        + "              \"The first three digits called the area number. The area number cannot be 000, 666, or between 900 and 999\",\n"
                        + "                \" Digits four and five are called the group number and range from 01 to 99\",\n"
                        + "              \"The last four digits are serial numbers from 0001 to 9999.\"");
                txtSsn.setBorder(BorderFactory.createLineBorder(Color.RED));

                return;
            }

            if (ssnPatternCheck()) {
                txtSsn.setBorder(BorderFactory.createLineBorder(Color.GRAY));

            }

            String address = txtAddr.getText().trim();

            String phone = txtPhn.getText().trim();

            if (!phnPtrnCheck()) {
                JOptionPane.showMessageDialog(null, "/* Following are valid phone number examples */             \n"
                        + "              \"1234567890\", \"123-456-7890\", \"(123)4567890\", \"(123)456-7890\",\n"
                        + "              /* Following are invalid phone numbers */ \n"
                        + "              \"(1234567890)\",\"123)4567890\", \"12345678901\", \"(1)234567890\",");
                txtPhn.setBorder(BorderFactory.createLineBorder(Color.RED));

                return;
            }

            if (phnPtrnCheck()) {
                txtPhn.setBorder(BorderFactory.createLineBorder(Color.GRAY));

            }

            String policyNumber = txtPlcyNum.getText().trim();
            String insurancePolicyName = txtInsPlcyNm.getSelectedItem().toString();

            double coverage = Double.parseDouble(txtInsCvrgPercent.getText().trim());

            try {
                Double.parseDouble(txtInsCvrgPercent.getText().trim());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please provide integer values in coverage textfield");
                return;
            }

            Insurance insurance = new Insurance(insurancePolicyName, insrCmnEntr.getName(), coverage);

            InsuranceCustomer insrCust = new InsuranceCustomer(insurance, policyNumber);

            insrCust.setCustFrstNm(firstName);
            insrCust.setCustLstNme(lastName);
            insrCust.setDob(dateOfBirth);
            insrCust.setGender(gender);
            insrCust.setSsn(ssn);
            insrCust.setPhNo(phone);
            insrCust.setAddress(address);

            insrCust.setIns(insurance);

            insrCmnEntr.getInsuranceCustomerDirectory().getInsCust().add(insrCust);

            insrCmnEntr.getInsuranceCustomerDirectory().getInsCust();

            pplTbl();
            refr();
            JOptionPane.showMessageDialog(null, "Customer is added");

        }

    }//GEN-LAST:event_btnAddCstmrActionPerformed

    private void txtInsPlcyNmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInsPlcyNmFocusGained
        System.out.println("Gained");
    }//GEN-LAST:event_txtInsPlcyNmFocusGained

    private void txtInsPlcyNmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsPlcyNmActionPerformed

        Insurance selectedPolicy = (Insurance) txtInsPlcyNm.getSelectedItem();
        txtInsCvrgPercent.setText(String.valueOf(selectedPolicy.getCoverage()));
    }//GEN-LAST:event_txtInsPlcyNmActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCstmr;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox cbGndr;
    private com.toedter.calendar.JDateChooser dobJDateChooser;
    private javax.swing.JLabel img;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddNewCust;
    private javax.swing.JLabel lblAddr;
    private javax.swing.JLabel lblAlCstmr;
    private javax.swing.JLabel lblDtOfBrth;
    private javax.swing.JLabel lblFrstNm;
    private javax.swing.JLabel lblGndr;
    private javax.swing.JLabel lblInsCvrgPercent;
    private javax.swing.JLabel lblInsInfo;
    private javax.swing.JLabel lblInsPlcyNm;
    private javax.swing.JLabel lblLstNm;
    private javax.swing.JLabel lblPhn;
    private javax.swing.JLabel lblPlcyNo;
    private javax.swing.JLabel lblPrsnlInfo;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JTable tblNewCstmr;
    private javax.swing.JTextField txtAddr;
    private javax.swing.JTextField txtFrstNm;
    private javax.swing.JTextField txtInsCvrgPercent;
    private javax.swing.JComboBox txtInsPlcyNm;
    private javax.swing.JTextField txtLstNm;
    private javax.swing.JTextField txtPhn;
    private javax.swing.JTextField txtPlcyNum;
    private javax.swing.JTextField txtSsn;
    // End of variables declaration//GEN-END:variables

    private boolean phnPtrnCheck() {

        Pattern pattern = Pattern.compile("\\d{10}|(?:\\d{3}-){2}\\d{4}|\\(\\d{3}\\)\\d{3}-?\\d{4}");
        Matcher matcher = pattern.matcher(txtPhn.getText());

        boolean b = false;

        if (matcher.matches()) {
            b = true;
        } else {
            b = false;
        }

        return b;
    }

    private boolean ssnPatternCheck() {

        Pattern pattern = Pattern.compile("^(?!000|666)[0-8][0-9]{2}-(?!00)[0-9]{2}-(?!0000)[0-9]{4}$");
        Matcher matcher = pattern.matcher(txtSsn.getText());

        boolean b = false;

        if (matcher.matches()) {
            b = true;
        } else {
            b = false;
        }

        return b;
    }

    private void refr() {

        txtPlcyNum.setText(UUID.randomUUID().toString().substring(0, 7));
        txtFrstNm.setText("");
        txtLstNm.setText("");
        txtPhn.setText("");
        txtSsn.setText("");
        dobJDateChooser.setDate(null);
        txtAddr.setText("");

    }

    private void populateFields() {
        txtPlcyNum.setText(plcyNum);
        List<Insurance> policies = insrCmnEntr.getInsPlcyDir().getInsurancePolicies();

        for (Insurance policy : policies) {
            txtInsPlcyNm.addItem(policy);
        }

        Insurance selectedPolicy = (Insurance) txtInsPlcyNm.getSelectedItem();
        
        if(selectedPolicy != null)
        {
        txtInsCvrgPercent.setText(String.valueOf(selectedPolicy.getCoverage()));
        }
        else{
            JOptionPane.showMessageDialog(null , "No Existing policy!");
            return;
        }

    }

    private void pplTbl() {
        DefaultTableModel dtm = (DefaultTableModel) tblNewCstmr.getModel();

        dtm.setRowCount(0);
        List<InsuranceCustomer> customers = insrCmnEntr.getInsuranceCustomerDirectory().getInsCust();
        for (InsuranceCustomer customer : customers) {
            Object[] row = new Object[4];
            row[0] = customer.getCustFrstNm() + " " + customer.getCustLstNme();
            row[1] = customer;
            row[2] = customer.getIns().getPolicyName();
            row[3] = customer.getIns().getCoverage();

            dtm.addRow(row);
        }
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(dtm);
        tblNewCstmr.setRowSorter(sorter);
    }
}
