/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InsuranceAgentRole;

import Business.Enterprise.Enterprise;
import Business.Org.Organization;
import Business.Org.OrgInsuranceFinance;
import Business.SystemUserAccount.SystemUsers;
import Business.WorkQueue.InsReq;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author ankitajha
 */

public class ProcessRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private SystemUsers account;
    private Enterprise enterprise;
    private InsReq insuranceWorkRequest;

    /**
     * Creates new form ProcessRequestJPanel
     */
    public ProcessRequestJPanel(JPanel userProcessContainer, SystemUsers userAccount, Enterprise enterprise, InsReq insuranceWorkRequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.insuranceWorkRequest = insuranceWorkRequest;
        this.account = userAccount;
        populateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPlcyNo = new javax.swing.JLabel();
        txtPlcyNo = new javax.swing.JTextField();
        lblClmAmt = new javax.swing.JLabel();
        txtClmAmt = new javax.swing.JTextField();
        lblMsg = new javax.swing.JLabel();
        txtMsg = new javax.swing.JTextField();
        btnAcptSndReqFinDept = new javax.swing.JButton();
        btnReqReq = new javax.swing.JButton();
        lblCstmrNm = new javax.swing.JLabel();
        txtCstmrNm = new javax.swing.JTextField();
        lblTtlBllAmt = new javax.swing.JLabel();
        txtTtlBllAmt = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        img = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        lblPlcyNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPlcyNo.setText("Policy Number");
        add(lblPlcyNo);
        lblPlcyNo.setBounds(203, 98, 88, 15);

        txtPlcyNo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtPlcyNo.setEnabled(false);
        add(txtPlcyNo);
        txtPlcyNo.setBounds(307, 96, 145, 24);

        lblClmAmt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblClmAmt.setText("Claim Amount");
        add(lblClmAmt);
        lblClmAmt.setBounds(204, 212, 85, 15);

        txtClmAmt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtClmAmt.setEnabled(false);
        add(txtClmAmt);
        txtClmAmt.setBounds(308, 210, 144, 24);

        lblMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMsg.setText("Message");
        add(lblMsg);
        lblMsg.setBounds(239, 250, 52, 15);

        txtMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMsgActionPerformed(evt);
            }
        });
        add(txtMsg);
        txtMsg.setBounds(309, 248, 265, 23);

        btnAcptSndReqFinDept.setBackground(new java.awt.Color(0, 102, 102));
        btnAcptSndReqFinDept.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAcptSndReqFinDept.setForeground(java.awt.Color.white);
        btnAcptSndReqFinDept.setText("Accept and Send Request To Finance Department");
        btnAcptSndReqFinDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcptSndReqFinDeptActionPerformed(evt);
            }
        });
        add(btnAcptSndReqFinDept);
        btnAcptSndReqFinDept.setBounds(121, 286, 322, 34);

        btnReqReq.setBackground(new java.awt.Color(0, 102, 102));
        btnReqReq.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReqReq.setForeground(java.awt.Color.white);
        btnReqReq.setText("Reject Request");
        btnReqReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqReqActionPerformed(evt);
            }
        });
        add(btnReqReq);
        btnReqReq.setBounds(455, 286, 131, 34);

        lblCstmrNm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCstmrNm.setText("Customer Name");
        add(lblCstmrNm);
        lblCstmrNm.setBounds(192, 136, 95, 15);

        txtCstmrNm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtCstmrNm.setEnabled(false);
        add(txtCstmrNm);
        txtCstmrNm.setBounds(306, 134, 146, 24);

        lblTtlBllAmt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTtlBllAmt.setText("Total Bill Amount");
        add(lblTtlBllAmt);
        lblTtlBllAmt.setBounds(185, 174, 105, 15);

        txtTtlBllAmt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtTtlBllAmt.setEnabled(false);
        add(txtTtlBllAmt);
        txtTtlBllAmt.setBounds(308, 172, 144, 24);

        btnBack.setBackground(new java.awt.Color(0, 153, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(10, 11, 93, 25);

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/InsurancePolicy.jpg"))); // NOI18N
        add(img);
        img.setBounds(90, -90, 930, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMsgActionPerformed

    private void btnAcptSndReqFinDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcptSndReqFinDeptActionPerformed

        String message = txtMsg.getText();
        if (message.equals("")) {
            JOptionPane.showMessageDialog(null, "Message is mandatory!");
            return;
        } else {
            insuranceWorkRequest.setWrkMsg(message);
            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");

            if (dialogResult == JOptionPane.YES_OPTION) {
                Organization org = null;
                for (Organization organization : enterprise.getOrgDir().getOrganizations()) {
                    if (organization instanceof OrgInsuranceFinance) {
                        org = organization;
                        break;
                    }
                }

                if (org != null) {
                    org.getWrkQ().getWrkReqs().add(insuranceWorkRequest);
                    account.getWorkQ().getWrkReqs().add(insuranceWorkRequest);
                }

                JOptionPane.showMessageDialog(null, "Request Approved and Sent To Finance Department");
                insuranceWorkRequest.setReqStatus("Sent To Finance Department");
                insuranceWorkRequest.setInsPlcyAgnt(account.getEmploye().getEmpName());
                insuranceWorkRequest.setRcvr(null);

                txtMsg.setText("");
                btnReqReq.setEnabled(false);
                btnAcptSndReqFinDept.setEnabled(false);

            }
            txtMsg.setText("");
        }
    }//GEN-LAST:event_btnAcptSndReqFinDeptActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AllInsuranceRequestsJPanel allInsuranceRequestsJPanel = (AllInsuranceRequestsJPanel) component;
        allInsuranceRequestsJPanel.pplTbl();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);


    }//GEN-LAST:event_btnBackActionPerformed

    private void btnReqReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqReqActionPerformed

        String message = txtMsg.getText();
        if (message.equals("")) {
            JOptionPane.showMessageDialog(null, "Message is mandatory!");
            return;
        } else {
            insuranceWorkRequest.setWrkMsg(message);

            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
            if (dialogResult == JOptionPane.YES_OPTION) {

                insuranceWorkRequest.setReqStatus("Rejected");
                insuranceWorkRequest.setWrkMsg(txtMsg.getText().trim());
                insuranceWorkRequest.setInsPlcyAgnt(account.getEmploye().getEmpName());
                txtMsg.setText("");
                btnReqReq.setEnabled(false);
                btnAcptSndReqFinDept.setEnabled(false);
            }
            txtMsg.setText("");
        }
    }//GEN-LAST:event_btnReqReqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcptSndReqFinDept;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReqReq;
    private javax.swing.JLabel img;
    private javax.swing.JLabel lblClmAmt;
    private javax.swing.JLabel lblCstmrNm;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblPlcyNo;
    private javax.swing.JLabel lblTtlBllAmt;
    private javax.swing.JTextField txtClmAmt;
    private javax.swing.JTextField txtCstmrNm;
    private javax.swing.JTextField txtMsg;
    private javax.swing.JTextField txtPlcyNo;
    private javax.swing.JTextField txtTtlBllAmt;
    // End of variables declaration//GEN-END:variables

    private void populateFields() {

        txtPlcyNo.setText(insuranceWorkRequest.getPolicyNumber());
        txtCstmrNm.setText(insuranceWorkRequest.getInsuranceCust().getCustFrstNm() + " " + insuranceWorkRequest.getInsuranceCust().getCustLstNme());
        txtTtlBllAmt.setText(String.valueOf(insuranceWorkRequest.getBillingAmt()));
        txtClmAmt.setText(String.valueOf(insuranceWorkRequest.getClmAmt()));

    }
}
