/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Org.OrgAccountant;
import Business.Org.Organization;
import Business.SystemUserAccount.SystemUsers;
import Business.WorkQueue.AccountBillRqst;
import Business.WorkQueue.PatientTreatmentReq;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Parth 
 */
public class RequestBillingJPanel extends javax.swing.JPanel {

    private JPanel jPanel;
    private SystemUsers usrAcnt;
    private Enterprise entrpz;
    private PatientTreatmentReq pntTrtmntWrkReq;
    private EcoSystem ecoSystem;
    private double cnsltChrg = 50;

    /**
     * Creates new form RequestBillingJPanel
     */
    RequestBillingJPanel(JPanel userProcessContainer, SystemUsers userAccount, Enterprise enterprise, PatientTreatmentReq workRequest) {
        initComponents();
        this.jPanel = userProcessContainer;
        this.usrAcnt = userAccount;
        this.entrpz = enterprise;
        this.pntTrtmntWrkReq = workRequest;
        pplTbl();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBillReq = new javax.swing.JLabel();
        lblPtntInfo = new javax.swing.JLabel();
        txtFrstNm = new javax.swing.JTextField();
        lblFrstNm = new javax.swing.JLabel();
        lblLstNm = new javax.swing.JLabel();
        txtLstNm = new javax.swing.JTextField();
        lblAssgnDr = new javax.swing.JLabel();
        txtAssgndDr = new javax.swing.JTextField();
        lblPtntId = new javax.swing.JLabel();
        txtPtntId = new javax.swing.JTextField();
        lblBillingInformation = new javax.swing.JLabel();
        lblConsultChargesUSD = new javax.swing.JLabel();
        txtConsultChargesUSD = new javax.swing.JTextField();
        lblMedicalChargesUSD = new javax.swing.JLabel();
        txtMedicalChargesUSD = new javax.swing.JTextField();
        lblLabTstChargeUSD = new javax.swing.JLabel();
        txtLabTestChargesUSD = new javax.swing.JTextField();
        lblMiscChargesUSD = new javax.swing.JLabel();
        txtMiscChargesUSD = new javax.swing.JTextField();
        btnSndBillReq = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        imgBillReq = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(null);

        lblBillReq.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblBillReq.setText("Billing Request");
        add(lblBillReq);
        lblBillReq.setBounds(310, 60, 157, 29);

        lblPtntInfo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPtntInfo.setText("PATIENT INFORMATION");
        add(lblPtntInfo);
        lblPtntInfo.setBounds(290, 220, 180, 17);

        txtFrstNm.setEditable(false);
        add(txtFrstNm);
        txtFrstNm.setBounds(220, 250, 131, 23);

        lblFrstNm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblFrstNm.setText("First Name :");
        add(lblFrstNm);
        lblFrstNm.setBounds(130, 260, 90, 17);

        lblLstNm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblLstNm.setText("Last Name :");
        add(lblLstNm);
        lblLstNm.setBounds(390, 260, 75, 17);

        txtLstNm.setEditable(false);
        add(txtLstNm);
        txtLstNm.setBounds(460, 250, 131, 23);

        lblAssgnDr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblAssgnDr.setText("Assigned Doctor :");
        add(lblAssgnDr);
        lblAssgnDr.setBounds(110, 290, 109, 17);

        txtAssgndDr.setEditable(false);
        add(txtAssgndDr);
        txtAssgndDr.setBounds(220, 290, 130, 23);

        lblPtntId.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPtntId.setText("Patient Id:");
        add(lblPtntId);
        lblPtntId.setBounds(390, 290, 66, 17);

        txtPtntId.setEditable(false);
        add(txtPtntId);
        txtPtntId.setBounds(460, 290, 131, 23);

        lblBillingInformation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBillingInformation.setText("BILLING INFORMATION");
        add(lblBillingInformation);
        lblBillingInformation.setBounds(300, 360, 162, 17);

        lblConsultChargesUSD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblConsultChargesUSD.setText("Consultaion Charges (USD) :");
        add(lblConsultChargesUSD);
        lblConsultChargesUSD.setBounds(230, 390, 179, 21);

        txtConsultChargesUSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultChargesUSDActionPerformed(evt);
            }
        });
        add(txtConsultChargesUSD);
        txtConsultChargesUSD.setBounds(410, 390, 82, 23);

        lblMedicalChargesUSD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMedicalChargesUSD.setText("Medication Charges (USD):");
        add(lblMedicalChargesUSD);
        lblMedicalChargesUSD.setBounds(240, 460, 168, 21);
        add(txtMedicalChargesUSD);
        txtMedicalChargesUSD.setBounds(410, 460, 82, 23);

        lblLabTstChargeUSD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblLabTstChargeUSD.setText("Lab Test Charges (USD) :");
        add(lblLabTstChargeUSD);
        lblLabTstChargeUSD.setBounds(240, 420, 158, 21);

        txtLabTestChargesUSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLabTestChargesUSDActionPerformed(evt);
            }
        });
        add(txtLabTestChargesUSD);
        txtLabTestChargesUSD.setBounds(410, 420, 82, 23);

        lblMiscChargesUSD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMiscChargesUSD.setText("Miscellaneous Charges (USD):");
        add(lblMiscChargesUSD);
        lblMiscChargesUSD.setBounds(220, 490, 187, 17);
        add(txtMiscChargesUSD);
        txtMiscChargesUSD.setBounds(410, 490, 82, 23);

        btnSndBillReq.setBackground(new java.awt.Color(0, 102, 102));
        btnSndBillReq.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSndBillReq.setForeground(new java.awt.Color(255, 255, 255));
        btnSndBillReq.setText("Send Billing Request");
        btnSndBillReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSndBillReqActionPerformed(evt);
            }
        });
        add(btnSndBillReq);
        btnSndBillReq.setBounds(300, 540, 145, 32);

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(80, 40, 63, 25);

        imgBillReq.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        imgBillReq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/patient_experience.gif"))); // NOI18N
        imgBillReq.setToolTipText("");
        imgBillReq.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(imgBillReq);
        imgBillReq.setBounds(28, 5, 1470, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLabTestChargesUSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLabTestChargesUSDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLabTestChargesUSDActionPerformed

    private void txtConsultChargesUSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultChargesUSDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultChargesUSDActionPerformed

    private void btnSndBillReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSndBillReqActionPerformed
        String consultationCharge = txtConsultChargesUSD.getText().trim();
        String labChargesStr = txtLabTestChargesUSD.getText();
        String miscellaneouschargesStr = txtMiscChargesUSD.getText();
        String medicationChargesStr = txtMedicalChargesUSD.getText();
        if (consultationCharge.equals("") || labChargesStr.equals("") || miscellaneouschargesStr.equals("") || medicationChargesStr.equals("")) {
            JOptionPane.showMessageDialog(null, "All fields are mandatory");
        } else {
            
            try {
                Double.parseDouble(consultationCharge);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please provide a Numeric value for Consultation Charges");
                return;
            }
            
            try {
                Integer.parseInt(labChargesStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please type a Numeric value for Lab Charges");
                return;
            }
            try {
                Integer.parseInt(miscellaneouschargesStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please type a Numeric value for Miscellaneous charges");
                return;
            }
            try {
                Integer.parseInt(medicationChargesStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please type a Numeric value for Medication charges");
                return;
            }
            double labCharges = Double.parseDouble(labChargesStr);
            double miscellaneouscharges = Double.parseDouble(miscellaneouschargesStr);
            double medicationCharges = Double.parseDouble(medicationChargesStr);
            double billingAmount = labCharges + cnsltChrg + medicationCharges + miscellaneouscharges;
            //request.setBillAmount(billingAmount);

            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
            if (dialogResult == JOptionPane.YES_OPTION) {
                pntTrtmntWrkReq.setReqStatus("Consultation Completed");

                AccountBillRqst accountantBillingRequest = new AccountBillRqst();
                accountantBillingRequest.setBillTotal(billingAmount);
                //  accountantBillingRequest.setPatientId(Integer.parseInt(txtPatientId.getText()));

                accountantBillingRequest.setSndr(usrAcnt);
                accountantBillingRequest.setReqStatus("Sent");

                accountantBillingRequest.setPatient(pntTrtmntWrkReq.getPatient());

                Organization org = null;
                for (Organization organization : entrpz.getOrgDir().getOrganizations()) {

                    if (organization instanceof OrgAccountant) {
                        org = organization;
                        break;
                    }
                }
                if (org != null) {

                    org.getWrkQ().getWrkReqs().add(accountantBillingRequest);
                    usrAcnt.getWorkQ().getWrkReqs().add(accountantBillingRequest);

                }

                JOptionPane.showMessageDialog(null, "Billing Request submitted successfully");
                btnSndBillReq.setEnabled(false);
            }
        }

    }//GEN-LAST:event_btnSndBillReqActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        jPanel.remove(this);
        Component[] componentArray = jPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel dwjp = (DoctorWorkAreaJPanel) component;
        dwjp.pplReqTbl();
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSndBillReq;
    private javax.swing.JLabel imgBillReq;
    private javax.swing.JLabel lblAssgnDr;
    private javax.swing.JLabel lblBillReq;
    private javax.swing.JLabel lblBillingInformation;
    private javax.swing.JLabel lblConsultChargesUSD;
    private javax.swing.JLabel lblFrstNm;
    private javax.swing.JLabel lblLabTstChargeUSD;
    private javax.swing.JLabel lblLstNm;
    private javax.swing.JLabel lblMedicalChargesUSD;
    private javax.swing.JLabel lblMiscChargesUSD;
    private javax.swing.JLabel lblPtntId;
    private javax.swing.JLabel lblPtntInfo;
    private javax.swing.JTextField txtAssgndDr;
    private javax.swing.JTextField txtConsultChargesUSD;
    private javax.swing.JTextField txtFrstNm;
    private javax.swing.JTextField txtLabTestChargesUSD;
    private javax.swing.JTextField txtLstNm;
    private javax.swing.JTextField txtMedicalChargesUSD;
    private javax.swing.JTextField txtMiscChargesUSD;
    private javax.swing.JTextField txtPtntId;
    // End of variables declaration//GEN-END:variables

    private void pplTbl() {


        txtFrstNm.setText(pntTrtmntWrkReq.getPatient().getPatFrstNm());
        txtLstNm.setText(pntTrtmntWrkReq.getPatient().getPatLstNm());
        txtPtntId.setText(String.valueOf(pntTrtmntWrkReq.getPatient().getPatId()));
        txtAssgndDr.setText(pntTrtmntWrkReq.getDrAssignd().getEmploye().getEmpName());
        txtConsultChargesUSD.setText(String.valueOf(cnsltChrg));


    }
}
