/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GovernmentTreasurerRole;

import Business.Enterprise.Enterprise;
import Business.Org.Organization;
import Business.Org.OrgTreasurer;
import Business.SystemUserAccount.SystemUsers;
import Business.WorkQueue.GovFundReq;
import Business.WorkQueue.WorkReq;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ankitajha
 */
public class TreasurerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TreasurerWorkAreaJPanel
     */
    private JPanel jPanel;
    private SystemUsers userAccount;
    private OrgTreasurer treasurerOrganization;
    private Enterprise enterprise;

    public TreasurerWorkAreaJPanel(JPanel jpanel, SystemUsers usrAcnt, Organization org, Enterprise entrpz) {
        initComponents();
        this.enterprise = entrpz;
        this.jPanel = jpanel;
        this.treasurerOrganization = (OrgTreasurer) org;
        this.userAccount = usrAcnt;

        pplTbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTrsrWrkArea = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTrsr = new javax.swing.JTable();
        btnAssgn = new javax.swing.JButton();
        btnPrcsReq = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(new java.awt.Color(255, 255, 255));

        lblTrsrWrkArea.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTrsrWrkArea.setText("Treasurer Work Area ");

        tblTrsr.setBackground(new java.awt.Color(204, 204, 204));
        tblTrsr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tblTrsr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Sender", "Receiver", "Status", "Amount", "Message", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTrsr);

        btnAssgn.setBackground(new java.awt.Color(0, 102, 102));
        btnAssgn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAssgn.setForeground(new java.awt.Color(255, 255, 255));
        btnAssgn.setText("Assign To Me");
        btnAssgn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssgnActionPerformed(evt);
            }
        });

        btnPrcsReq.setBackground(new java.awt.Color(0, 102, 102));
        btnPrcsReq.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPrcsReq.setForeground(new java.awt.Color(255, 255, 255));
        btnPrcsReq.setText("Process Request");
        btnPrcsReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrcsReqActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/moneyimg.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTrsrWrkArea, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(214, 214, 214))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAssgn)
                                .addGap(77, 77, 77)
                                .addComponent(btnPrcsReq)
                                .addGap(212, 212, 212))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(433, 433, 433)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(453, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblTrsrWrkArea)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssgn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrcsReq, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssgnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssgnActionPerformed
        int selectedRow = tblTrsr.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first from the table to view details");
            return;
        } else {
            WorkReq req = (GovFundReq) tblTrsr.getValueAt(selectedRow, 5);
            if (req.getReqStatus().equals("Sent to Treasurer")) {
                req.setRcvr(userAccount);
                req.setReqStatus("Pending on " + req.getRcvr().getEmploye().getEmpName());
                pplTbl();
                JOptionPane.showMessageDialog(null, "Success !! Request is assigned to you ");
            } else {
                JOptionPane.showMessageDialog(null, "Can't assign this work request, as the work request is in " + req.getReqStatus() + " status", "Warning!", JOptionPane.WARNING_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnAssgnActionPerformed

    private void btnPrcsReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrcsReqActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblTrsr.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first from the table to view details");
            return;
        } else {
            GovFundReq req = (GovFundReq) tblTrsr.getValueAt(selectedRow, 5);
            if (req.getReqStatus().equalsIgnoreCase("Sent to Treasurer")) {
                JOptionPane.showMessageDialog(null, "Please assign selected request first");
                return;
            }
            if (req.getReqStatus().equalsIgnoreCase("Accepted")) {
                JOptionPane.showMessageDialog(null, "Request already completed", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (!userAccount.equals(req.getRcvr())) {
                JOptionPane.showMessageDialog(null, "Not Authorized", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (!userAccount.equals(req.getRcvr())) {
                JOptionPane.showMessageDialog(null, "Not Authorized", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (!userAccount.getEmploye().equals(req.getRcvr().getEmploye())) {
                JOptionPane.showMessageDialog(null, "Request assigned to other Officer", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (req.getReqStatus().equals("Rejected")) {
                JOptionPane.showMessageDialog(null, "Cannot process a Rejected Request", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            //request.setStatus("Processing");
            TreasurerProcessWorkRequestJPanel trrPrcsWrkReqJPanel = new TreasurerProcessWorkRequestJPanel(jPanel, req);
            jPanel.add("TreasurerProcessWorkRequestJPanel", trrPrcsWrkReqJPanel);
            CardLayout layout = (CardLayout) jPanel.getLayout();
            layout.next(jPanel);
        }
    }//GEN-LAST:event_btnPrcsReqActionPerformed

    public void pplTbl() {
        DefaultTableModel model = (DefaultTableModel) tblTrsr.getModel();
        model.setRowCount(0);

        for (WorkReq request : treasurerOrganization.getWrkQ().getWrkReqs()) {
            String status = request.getReqStatus();
            Object[] row = new Object[6];
            row[0] = request.getSndr().getEmploye().getEmpName();
            if (status.equalsIgnoreCase("Sent to Treasurer") || status.equalsIgnoreCase("Sent to Secretary")) {
                row[1] = null;
            } else {
                row[1] = request.getRcvr() == null ? null : request.getRcvr().getEmploye().getEmpName();
            }

            row[2] = status;
            row[3] = ((GovFundReq) request).getAmountRequested();
            row[4] = ((GovFundReq) request).getWrkMsg();
            row[5] = request;

            model.addRow(row);
        }
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblTrsr.setRowSorter(sorter);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssgn;
    private javax.swing.JButton btnPrcsReq;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTrsrWrkArea;
    private javax.swing.JTable tblTrsr;
    // End of variables declaration//GEN-END:variables
}
