/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LabAssistantRole;

import Business.EcoSystem;
import Business.Org.OrgLab;
import Business.Org.Organization;
import Business.SystemUserAccount.SystemUsers;
import Business.WorkQueue.PatientTreatmentReq;
import Business.WorkQueue.WorkReq;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ankitajha
 */
public class LabAssistantWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private SystemUsers userAccount;
    private OrgLab labOrganization;

    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public LabAssistantWorkAreaJPanel(JPanel userProcessContainer, SystemUsers account, Organization organization, EcoSystem business) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.labOrganization = (OrgLab) organization;

        popLabAsstTbl();
    }

    public void popLabAsstTbl() {
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        model.setRowCount(0);

        for (WorkReq request : labOrganization.getWrkQ().getWrkReqs()) {
            Object[] row = new Object[7];
            row[0] = request;
            row[1] = request.getSndr().getEmploye().getEmpName();
            row[2] = ((PatientTreatmentReq) request).getLabAssitantEmployee();
            row[3] = request.getReqStatus();
            row[4] = ((PatientTreatmentReq) request).getPatient().getPatFrstNm() + " " + ((PatientTreatmentReq) request).getPatient().getPatLstNm();
            row[5] = ((PatientTreatmentReq) request).getPatient().getPatId();
            row[6] = ((PatientTreatmentReq) request).getTypeOfTest();
            model.addRow(row);
        }
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tbl.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btnAssgndToMe = new javax.swing.JButton();
        btnProcess = new javax.swing.JButton();
        img = new javax.swing.JLabel();
        btnBldTst = new javax.swing.JButton();
        btnMriScan = new javax.swing.JButton();
        btnXray = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 51, 51));
        setLayout(null);

        tbl.setBackground(new java.awt.Color(204, 204, 204));
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status", "Patient Name", "Patient Id", "Test Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 730, 90);

        btnAssgndToMe.setBackground(new java.awt.Color(0, 153, 255));
        btnAssgndToMe.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAssgndToMe.setText("Assign to me");
        btnAssgndToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssgndToMeActionPerformed(evt);
            }
        });
        add(btnAssgndToMe);
        btnAssgndToMe.setBounds(10, 130, 140, 40);

        btnProcess.setBackground(new java.awt.Color(0, 153, 255));
        btnProcess.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        add(btnProcess);
        btnProcess.setBounds(600, 130, 140, 40);

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/scanner.gif"))); // NOI18N
        add(img);
        img.setBounds(10, 180, 710, 370);

        btnBldTst.setBackground(new java.awt.Color(0, 153, 255));
        btnBldTst.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBldTst.setText("Blood Test");
        btnBldTst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBldTstActionPerformed(evt);
            }
        });
        add(btnBldTst);
        btnBldTst.setBounds(150, 130, 140, 40);

        btnMriScan.setBackground(new java.awt.Color(0, 153, 255));
        btnMriScan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnMriScan.setText("MRI scan");
        btnMriScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMriScanActionPerformed(evt);
            }
        });
        add(btnMriScan);
        btnMriScan.setBounds(450, 130, 140, 40);

        btnXray.setBackground(new java.awt.Color(0, 153, 255));
        btnXray.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnXray.setText("X Ray");
        btnXray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXrayActionPerformed(evt);
            }
        });
        add(btnXray);
        btnXray.setBounds(290, 130, 140, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssgndToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssgndToMeActionPerformed

        int selectedRow = tbl.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please select a row first");
            return;
        }

        PatientTreatmentReq request = (PatientTreatmentReq) tbl.getValueAt(selectedRow, 0);
        if (request.getLabAssitantEmployee() == null) {
            if (request.getReqStatus().equalsIgnoreCase("SentToLab")) {
                request.setLabAssitantEmployee(userAccount);
                request.setReqStatus("Pending on Lab Assistant");
                //  request.setReceiver(userAccount);
                popLabAsstTbl();
                JOptionPane.showMessageDialog(null, "The request is assigned to You!");
            } else {
                JOptionPane.showMessageDialog(null, "Cannot assign this lab request as the current status is: " + request.getReqStatus());
            }
        }
        else
        {
            if(userAccount.equals(request.getLabAssitantEmployee()))
            {
                JOptionPane.showMessageDialog(null,"Request is already assigned to you");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Request is assigned to other Lab Assistant");
            }
        }

    }//GEN-LAST:event_btnAssgndToMeActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed

        int selectedRow = tbl.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }

        PatientTreatmentReq request = (PatientTreatmentReq) tbl.getValueAt(selectedRow, 0);

       // request.setStatus("Processing");
        ProcessWorkRequestJPanel processWorkRequestJPanel = new ProcessWorkRequestJPanel(userProcessContainer, request);
        if (request.getLabAssitantEmployee() != null) {
            if (userAccount.equals(request.getLabAssitantEmployee())) {
                if (request.getReqStatus().equalsIgnoreCase("Pending on Lab Assistant")) {

                    userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                } else {
                    JOptionPane.showMessageDialog(null, "Cannot process the request as the status is: " + request.getReqStatus());
                }

            } else {

                JOptionPane.showMessageDialog(null, "Not authorised to process the request");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please assign the request first");
        }
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnBldTstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBldTstActionPerformed

        int selectedRow = tbl.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please select a row first");
            return;
        }

        PatientTreatmentReq request = (PatientTreatmentReq) tbl.getValueAt(selectedRow, 0);
        if(userAccount.equals(request.getLabAssitantEmployee()))
            {   
                if(request.getReqStatus().equalsIgnoreCase("Pending on Lab Assistant")){
                    request.setTypeOfTest("Blood Test");
                }else{
                    JOptionPane.showMessageDialog(null, "Test is already done!");
                }
                
            }else{
            JOptionPane.showMessageDialog(null, "Lab assistant is not assigned cannot modify the type of test");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBldTstActionPerformed

    private void btnMriScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMriScanActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tbl.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please select a row first");
            return;
        }

        PatientTreatmentReq request = (PatientTreatmentReq) tbl.getValueAt(selectedRow, 0);
        if(userAccount.equals(request.getLabAssitantEmployee()))
            {   
                if(request.getReqStatus().equalsIgnoreCase("Pending on Lab Assistant")){
                    request.setTypeOfTest("MRI Scan");
                }else{
                    JOptionPane.showMessageDialog(null, "Test is already done!");
                }
                
            }else{
            JOptionPane.showMessageDialog(null, "Lab assistant is not assigned cannot modify the type of blood test");
        }
    }//GEN-LAST:event_btnMriScanActionPerformed

    private void btnXrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXrayActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tbl.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please select a row first");
            return;
        }

        PatientTreatmentReq request = (PatientTreatmentReq) tbl.getValueAt(selectedRow, 0);
        if(userAccount.equals(request.getLabAssitantEmployee()))
            {   
                if(request.getReqStatus().equalsIgnoreCase("Pending on Lab Assistant")){
                    request.setTypeOfTest("X Ray");
                }else{
                    JOptionPane.showMessageDialog(null, "Test is already done!");
                }
                
            }else{
            JOptionPane.showMessageDialog(null, "Lab assistant is not assigned cannot modify the type of blood test");
        }
    }//GEN-LAST:event_btnXrayActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssgndToMe;
    private javax.swing.JButton btnBldTst;
    private javax.swing.JButton btnMriScan;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnXray;
    private javax.swing.JLabel img;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
