/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LabAssistantRole;


import Business.WorkQueue.PatientTreatmentReq;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ankitajha
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    PatientTreatmentReq patientTreatmentWorkRequest;

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ProcessWorkRequestJPanel(JPanel userProcessContainer, PatientTreatmentReq patientTreatmentWorkRequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patientTreatmentWorkRequest = patientTreatmentWorkRequest;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSbmtRslt = new javax.swing.JButton();
        lblRslt = new javax.swing.JLabel();
        txtLbRst = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblLbTstReq = new javax.swing.JLabel();
        img = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        btnSbmtRslt.setBackground(new java.awt.Color(0, 102, 102));
        btnSbmtRslt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSbmtRslt.setForeground(java.awt.Color.white);
        btnSbmtRslt.setText("Submit Result");
        btnSbmtRslt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSbmtRsltActionPerformed(evt);
            }
        });
        add(btnSbmtRslt);
        btnSbmtRslt.setBounds(500, 170, 131, 36);

        lblRslt.setBackground(new java.awt.Color(255, 255, 255));
        lblRslt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblRslt.setText("Result");
        add(lblRslt);
        lblRslt.setBounds(440, 130, 38, 17);
        add(txtLbRst);
        txtLbRst.setBounds(490, 120, 160, 30);

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText(" Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(10, 11, 75, 29);

        lblLbTstReq.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblLbTstReq.setText("Lab Test Results");
        add(lblLbTstReq);
        lblLbTstReq.setBounds(230, 20, 171, 29);

        img.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/labassis.jpeg"))); // NOI18N
        add(img);
        img.setBounds(30, 70, 650, 460);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LabAssistantWorkAreaJPanel dwjp = (LabAssistantWorkAreaJPanel) component;
        dwjp.popLabAsstTbl();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSbmtRsltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSbmtRsltActionPerformed
        String labResult = txtLbRst.getText().trim();
        if (labResult.equals("")) {
            JOptionPane.showMessageDialog(null, "Result is mandatory");
            return;
        } else {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
            if (dialogResult == JOptionPane.YES_OPTION) {
                patientTreatmentWorkRequest.setResultFromLab(labResult);
                patientTreatmentWorkRequest.setReqStatus("Lab Test Completed");
                JOptionPane.showMessageDialog(null, "Result submitted successfully");
                txtLbRst.setText("");
                btnSbmtRslt.setEnabled(false);
            }

        }


    }//GEN-LAST:event_btnSbmtRsltActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSbmtRslt;
    private javax.swing.JLabel img;
    private javax.swing.JLabel lblLbTstReq;
    private javax.swing.JLabel lblRslt;
    private javax.swing.JTextField txtLbRst;
    // End of variables declaration//GEN-END:variables
}
