 /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Employee.Staff;
import Business.Org.Organization;
import Business.Org.OrgDirectory;
import Business.Org.OrgPatient;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Pratik
 */
public class ManageEmployeeJPanel extends javax.swing.JPanel {

    private OrgDirectory orgDir;
    private JPanel jPanel;

    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageEmployeeJPanel(JPanel userProcessContainer, OrgDirectory organizationDir) {
        initComponents();
        this.jPanel = userProcessContainer;
        this.orgDir = organizationDir;

        pplOrgCmbx();
        pplOrgEmpCmbx();
    }

    public void pplOrgCmbx() {
        cbOrg.removeAllItems();

        for (Organization organization : orgDir.getOrganizations()) {

            if (!(organization instanceof OrgPatient)) {
                cbOrg.addItem(organization);
            }
        }
        DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        organizationJTable.setRowSorter(sorter);
    }

    public void pplOrgEmpCmbx() {
        cbEmpOrg.removeAllItems();

        for (Organization organization : orgDir.getOrganizations()) {

            if (!(organization instanceof OrgPatient)) {
                cbEmpOrg.addItem(organization);
            }
        }
    }

    private void pplTbl(Organization organization) {
        DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();

        model.setRowCount(0);

      
        for (Staff emp : organization.getEmpDir().getEmpList()) {
            Object[] row = new Object[2];
            row[0] = emp.getEmpId()-5;
            row[1] = emp.getEmpName();

            model.addRow(row);
        }
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        organizationJTable.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblOrg = new javax.swing.JScrollPane();
        organizationJTable = new javax.swing.JTable();
        btnEmpCreation = new javax.swing.JButton();
        cbOrg = new javax.swing.JComboBox();
        lblOrg = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        cbEmpOrg = new javax.swing.JComboBox();
        lblOrganization = new javax.swing.JLabel();
        lblEmp = new javax.swing.JLabel();
        imgManageEmployee = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setForeground(new java.awt.Color(255, 255, 255));

        organizationJTable.setBackground(new java.awt.Color(204, 204, 204));
        organizationJTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrg.setViewportView(organizationJTable);
        if (organizationJTable.getColumnModel().getColumnCount() > 0) {
            organizationJTable.getColumnModel().getColumn(0).setResizable(false);
            organizationJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        btnEmpCreation.setBackground(new java.awt.Color(0, 102, 102));
        btnEmpCreation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEmpCreation.setText("Create Employee");
        btnEmpCreation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpCreationActionPerformed(evt);
            }
        });

        cbOrg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrgActionPerformed(evt);
            }
        });

        lblOrg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblOrg.setText("Organization");

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText(" Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblName.setText("Name");

        txtName.setBackground(new java.awt.Color(204, 204, 204));
        txtName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        cbEmpOrg.setBackground(new java.awt.Color(204, 204, 204));
        cbEmpOrg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbEmpOrg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEmpOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEmpOrgActionPerformed(evt);
            }
        });

        lblOrganization.setBackground(new java.awt.Color(204, 204, 204));
        lblOrganization.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblOrganization.setText("Organization");

        lblEmp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblEmp.setText("Manage Employee");

        imgManageEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgManageEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HospitalEmployee.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(tblOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(lblOrg))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnBack)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmp)
                            .addComponent(cbOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOrganization)
                            .addComponent(lblName))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbEmpOrg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEmpCreation)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(imgManageEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(406, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblEmp))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEmpOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrganization))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEmpCreation, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgManageEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpCreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpCreationActionPerformed

        Organization organization = (Organization) cbEmpOrg.getSelectedItem();
        String name = txtName.getText();
        if (name == null || name.equals("")) {
            JOptionPane.showMessageDialog(null, "Name Cannot be empty!");
            return;
        }

        organization.getEmpDir().createEmployee(name);
        pplTbl(organization);

        txtName.setText("");

    }//GEN-LAST:event_btnEmpCreationActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        jPanel.remove(this);
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrgActionPerformed
        Organization organization = (Organization) cbOrg.getSelectedItem();
        if (organization != null) {
            pplTbl(organization);
        }
    }//GEN-LAST:event_cbOrgActionPerformed

    private void cbEmpOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEmpOrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEmpOrgActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEmpCreation;
    private javax.swing.JComboBox cbEmpOrg;
    private javax.swing.JComboBox cbOrg;
    private javax.swing.JLabel imgManageEmployee;
    private javax.swing.JLabel lblEmp;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrg;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JTable organizationJTable;
    private javax.swing.JScrollPane tblOrg;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
