/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.AdministrativeRole;

import Business.Networks.Networks;
import Business.Org.Organization;
import Business.WorkQueue.NGOFundRequest;
import Business.WorkQueue.*;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Pratik
 */
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Org.OrgNGOAdmin;
import Business.SystemUserAccount.SystemUsers;
import Business.WorkQueue.WorkReq;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
public class NGORequestFundsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private SystemUsers userAccount;
    private EcoSystem ecoSystem;
    
    /**
     * Creates new form NGORequestFunds
     */
    public NGORequestFundsJPanel(JPanel jPanel, Enterprise enterprise, SystemUsers userAccount, EcoSystem ecoSystem) {
        
        initComponents();
        this.userProcessContainer = jPanel;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.ecoSystem = ecoSystem;
        populateNGORequestTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblReqFund = new javax.swing.JLabel();
        lblTotalContriRcvd = new javax.swing.JLabel();
        txtTotalNgoFundsReceived = new javax.swing.JTextField();
        lblAllContriReq = new javax.swing.JLabel();
        lblHospAdd = new javax.swing.JLabel();
        txthospitalAddr = new javax.swing.JTextField();
        lblHospReqAmt = new javax.swing.JLabel();
        txthospitalAmt = new javax.swing.JTextField();
        txthospitalName = new javax.swing.JTextField();
        txtHospName = new javax.swing.JLabel();
        btnReqFundFrmNgo = new javax.swing.JButton();
        tblAllContriReq = new javax.swing.JScrollPane();
        tblNgoReq = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblReqFund.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblReqFund.setText("Request Funds from NGO");

        lblTotalContriRcvd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblTotalContriRcvd.setText("Total Contributions Received :");

        txtTotalNgoFundsReceived.setEditable(false);
        txtTotalNgoFundsReceived.setBackground(new java.awt.Color(204, 204, 204));
        txtTotalNgoFundsReceived.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lblAllContriReq.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAllContriReq.setText("All Contributions Requests");

        lblHospAdd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblHospAdd.setText("Hospital Address");

        txthospitalAddr.setBackground(new java.awt.Color(204, 204, 204));
        txthospitalAddr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lblHospReqAmt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblHospReqAmt.setText("Hospital's required Amount");

        txthospitalAmt.setBackground(new java.awt.Color(204, 204, 204));
        txthospitalAmt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txthospitalName.setBackground(new java.awt.Color(204, 204, 204));
        txthospitalName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtHospName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtHospName.setText("Hospital Name");

        btnReqFundFrmNgo.setBackground(new java.awt.Color(0, 102, 102));
        btnReqFundFrmNgo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnReqFundFrmNgo.setText("Request Funds from NGO");
        btnReqFundFrmNgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqFundFrmNgoActionPerformed(evt);
            }
        });

        tblNgoReq.setBackground(new java.awt.Color(204, 204, 204));
        tblNgoReq.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tblNgoReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hospital Name", "Hospital Address", "Hospital Contribution", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAllContriReq.setViewportView(tblNgoReq);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NGO.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHospReqAmt)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtHospName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHospAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txthospitalAmt)
                                .addComponent(txthospitalAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txthospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotalContriRcvd)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotalNgoFundsReceived, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblAllContriReq, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReqFundFrmNgo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tblAllContriReq, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnBack)
                                    .addGap(103, 103, 103)
                                    .addComponent(lblReqFund, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(lblReqFund, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHospName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHospAdd)
                    .addComponent(txthospitalAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHospReqAmt)
                            .addComponent(txthospitalAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(btnReqFundFrmNgo)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalNgoFundsReceived, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalContriRcvd))
                        .addGap(33, 33, 33)
                        .addComponent(lblAllContriReq, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tblAllContriReq, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnReqFundFrmNgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqFundFrmNgoActionPerformed
     // TODO add your handling code here:

        String hospname = txthospitalName.getText();
        String hospaddress = txthospitalAddr.getText();
        String neededamtreq = txthospitalAmt.getText();

        if(hospname.equals("") || hospaddress.equals("")||neededamtreq.equals("")){
            JOptionPane.showMessageDialog(null, "All fields are mandatory");
        }else {
            try {
                Integer.parseInt(neededamtreq);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please type an Integer value for contribution");
                return;
            }

            NGOFundRequest ngoFundRequest = new NGOFundRequest(hospname,hospaddress, Integer.parseInt(neededamtreq));
            ngoFundRequest.setSndr(userAccount);
            ngoFundRequest.setReqStatus("Sent");
            Organization org = null;

            List<Networks> networks = ecoSystem.getNetworks();

            for (Networks network : networks) {

                List<Enterprise> enterprises = network.getEntDir().getEnterpriseList();
                for (Enterprise enterprise : enterprises) {
                    List<Organization> organizations = enterprise.getOrgDir().getOrganizations();
                    for (Organization organization : organizations) {
                        if (organization instanceof OrgNGOAdmin) {
                            org = organization;
                            break;
                        }
                    }
                }
            }

            if (org != null) {
                org.getWrkQ().getWrkReqs().add(ngoFundRequest);
                userAccount.getWorkQ().getWrkReqs().add(ngoFundRequest);
            }
            populateNGORequestTable();
        }

    }//GEN-LAST:event_btnReqFundFrmNgoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReqFundFrmNgo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAllContriReq;
    private javax.swing.JLabel lblHospAdd;
    private javax.swing.JLabel lblHospReqAmt;
    private javax.swing.JLabel lblReqFund;
    private javax.swing.JLabel lblTotalContriRcvd;
    private javax.swing.JScrollPane tblAllContriReq;
    private javax.swing.JTable tblNgoReq;
    private javax.swing.JLabel txtHospName;
    private javax.swing.JTextField txtTotalNgoFundsReceived;
    private javax.swing.JTextField txthospitalAddr;
    private javax.swing.JTextField txthospitalAmt;
    private javax.swing.JTextField txthospitalName;
    // End of variables declaration//GEN-END:variables

    private void populateNGORequestTable() {
        DefaultTableModel model = (DefaultTableModel) tblNgoReq.getModel();
        int totalreqFunds = 0;
        model.setRowCount(0);
        for (WorkReq request : userAccount.getWorkQ().getWrkReqs()) {
            if(request instanceof NGOFundRequest){
            Object[] row = new Object[4];
            row[0] = String.valueOf(((NGOFundRequest) request).getNameOfHospital());
            row[1] = String.valueOf(((NGOFundRequest) request).getAddressOfHospital());
            row[2] = String.valueOf(((NGOFundRequest) request).getAmountRequired());
            row[3] = request.getReqStatus();
            model.addRow(row);
            if (request.getReqStatus().equalsIgnoreCase("Accepted")) {
                totalreqFunds += ((NGOFundRequest) request).getAmountRequired();
            }
            }
        }

        txtTotalNgoFundsReceived.setText(String.valueOf(totalreqFunds));
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblNgoReq.setRowSorter(sorter);
    }

}
