/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HealthcareOfficerRole;

import Business.Enterprise.Enterprise;
import Business.Org.Organization;
import Business.Org.OrgSecretary;
import Business.SystemUserAccount.SystemUsers;
import Business.WorkQueue.GovFundReq;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pratik
 */
public class OfficerProcessWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    private JPanel jPanel;
    private Enterprise entrpz;
    private SystemUsers usrAcnt;
    private GovFundReq govtFndReq;
    private OfficerWorkAreaJPanel ofcrWrAreaJPanel;

    public OfficerProcessWorkRequestJPanel(JPanel jPanel, SystemUsers userAccount, GovFundReq fundRequest, Enterprise enterprise) {
        initComponents();

        this.jPanel = jPanel;
        this.entrpz = enterprise;
        this.usrAcnt = userAccount;
        this.govtFndReq = fundRequest;
        txtAmt.setText(String.valueOf(govtFndReq.getAmountRequested()));
        txtLoc.setText(govtFndReq.getLoc());
        txtPop.setText(String.valueOf(govtFndReq.getPopulation()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAmt = new javax.swing.JTextField();
        lblAmt = new javax.swing.JLabel();
        lblMsg = new javax.swing.JLabel();
        txtmsg = new javax.swing.JTextField();
        lblOfcReqPrcsArea = new javax.swing.JLabel();
        btnSndReqToSecToApprv = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblLocation = new javax.swing.JLabel();
        txtLoc = new javax.swing.JTextField();
        txtPop = new javax.swing.JTextField();
        lblPop = new javax.swing.JLabel();
        btnReq = new javax.swing.JButton();
        imgOfcPrcsWrkReq = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));

        txtAmt.setBackground(new java.awt.Color(204, 204, 204));
        txtAmt.setEnabled(false);

        lblAmt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblAmt.setText("Amount");

        lblMsg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMsg.setText("Message");

        txtmsg.setBackground(new java.awt.Color(204, 204, 204));

        lblOfcReqPrcsArea.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblOfcReqPrcsArea.setText("Officer Request Process area ");

        btnSndReqToSecToApprv.setBackground(new java.awt.Color(0, 102, 102));
        btnSndReqToSecToApprv.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSndReqToSecToApprv.setText("Send Request to Secretary to approve");
        btnSndReqToSecToApprv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSndReqToSecToApprvActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblLocation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblLocation.setText("Location");

        txtLoc.setBackground(new java.awt.Color(204, 204, 204));
        txtLoc.setEnabled(false);

        txtPop.setBackground(new java.awt.Color(204, 204, 204));
        txtPop.setEnabled(false);

        lblPop.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPop.setText("Population");

        btnReq.setBackground(new java.awt.Color(0, 102, 102));
        btnReq.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnReq.setText("Reject");
        btnReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqActionPerformed(evt);
            }
        });

        imgOfcPrcsWrkReq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/OfficeProcess.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnBack)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblAmt, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblLocation, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(38, 38, 38)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblMsg)
                                        .addComponent(lblPop))
                                    .addGap(38, 38, 38)
                                    .addComponent(txtPop, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblOfcReqPrcsArea)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReq, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSndReqToSecToApprv))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(imgOfcPrcsWrkReq, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblOfcReqPrcsArea))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLocation)
                    .addComponent(txtLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPop))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMsg))
                .addGap(49, 49, 49)
                .addComponent(btnSndReqToSecToApprv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReq, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
            .addComponent(imgOfcPrcsWrkReq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        jPanel.remove(this);
        Component[] componentArray = jPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        OfficerWorkAreaJPanel owjp = (OfficerWorkAreaJPanel) component;
        owjp.pplTbl();
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSndReqToSecToApprvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSndReqToSecToApprvActionPerformed
        // TODO add your handling code here:

        String msg = txtmsg.getText();
        if (msg.equals("")) {
            JOptionPane.showMessageDialog(null, "Message is mandatory!");
            return;
        } else {
            govtFndReq.setWrkMsg(msg);

            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");

            if (dialogResult == JOptionPane.YES_OPTION) {

                govtFndReq.setSndr(usrAcnt);
                govtFndReq.setReqStatus("Sent to Secretary");

                Organization org = null;
                for (Organization organization : entrpz.getOrgDir().getOrganizations()) {
                    if (organization instanceof OrgSecretary) {
                        org = organization;
                        break;
                    }
                }
                if (org != null) {
                    org.getWrkQ().getWrkReqs().add(govtFndReq);
                    usrAcnt.getWorkQ().getWrkReqs().add(govtFndReq);
                }
                JOptionPane.showMessageDialog(null, "Request to Secretary Successful!!!");
                txtmsg.setText("");
                btnReq.setEnabled(false);
                btnSndReqToSecToApprv.setEnabled(false);
            }
            txtmsg.setText("");
        }

    }//GEN-LAST:event_btnSndReqToSecToApprvActionPerformed

    private void btnReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqActionPerformed
        String msg = txtmsg.getText();
        if (msg.equals("")) {
            JOptionPane.showMessageDialog(null, "Message is mandatory!");
            return;
        } else {
            govtFndReq.setWrkMsg(msg);
            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");

            if (dialogResult == JOptionPane.YES_OPTION) {
                govtFndReq.setReqStatus("Rejected");
                txtmsg.setText("");
                btnReq.setEnabled(false);
                btnSndReqToSecToApprv.setEnabled(false);
            }

            txtmsg.setText("");
        }
    }//GEN-LAST:event_btnReqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReq;
    private javax.swing.JButton btnSndReqToSecToApprv;
    private javax.swing.JLabel imgOfcPrcsWrkReq;
    private javax.swing.JLabel lblAmt;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblOfcReqPrcsArea;
    private javax.swing.JLabel lblPop;
    private javax.swing.JTextField txtAmt;
    private javax.swing.JTextField txtLoc;
    private javax.swing.JTextField txtPop;
    private javax.swing.JTextField txtmsg;
    // End of variables declaration//GEN-END:variables
}
