/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HealthcareOfficerRole;

import Business.Enterprise.Enterprise;
import Business.Org.OrgHealthCareOfficial;
import Business.Org.Organization;
import Business.SystemUserAccount.SystemUsers;
import Business.WorkQueue.GovFundReq;
import Business.WorkQueue.WorkReq;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Pratik
 */
public class OfficerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel jPanel;
    private SystemUsers usrAcnt;
    private OrgHealthCareOfficial hlthCrOfcrJPanel;
    private Enterprise entrpz;

    /**
     * Creates new form OfficerWorkAreaJPanel1
     */
    public OfficerWorkAreaJPanel(JPanel jpanel, SystemUsers userAccount, Organization organization, Enterprise enterprise) {
        initComponents();
        this.entrpz = enterprise;

        this.jPanel = jpanel;

        this.hlthCrOfcrJPanel = (OrgHealthCareOfficial) organization;
        this.usrAcnt = userAccount;

        pplTbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGovHealthOfcrWrkArea = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWrkReqTbl = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        btnProcessReq = new javax.swing.JButton();
        btnVrcfnOnMap = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));

        lblGovHealthOfcrWrkArea.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblGovHealthOfcrWrkArea.setText("Government Health Officer Work Area");

        tblWrkReqTbl.setBackground(new java.awt.Color(204, 204, 204));
        tblWrkReqTbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tblWrkReqTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Location", "Sender", "Receiver", "Status", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWrkReqTbl);

        btnAssign.setBackground(new java.awt.Color(0, 102, 102));
        btnAssign.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAssign.setText("Assign To Me");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        btnProcessReq.setBackground(new java.awt.Color(0, 102, 102));
        btnProcessReq.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnProcessReq.setText("Process Request");
        btnProcessReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessReqActionPerformed(evt);
            }
        });

        btnVrcfnOnMap.setBackground(new java.awt.Color(0, 102, 102));
        btnVrcfnOnMap.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnVrcfnOnMap.setText("Verification on Map");
        btnVrcfnOnMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVrcfnOnMapActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/OfficeProcess.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(lblGovHealthOfcrWrkArea, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171)
                        .addComponent(btnVrcfnOnMap))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(btnProcessReq)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel2)
                .addGap(0, 750, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblGovHealthOfcrWrkArea, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVrcfnOnMap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProcessReq, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(252, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = tblWrkReqTbl.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first from the table to view details");
            return;
        } else {
            WorkReq req = (GovFundReq) tblWrkReqTbl.getValueAt(selectedRow, 0);
            if (req.getReqStatus().equals("Sent")) {
                req.setRcvr(usrAcnt);
                req.setReqStatus("Pending on " + req.getRcvr().getEmploye().getEmpName());
                pplTbl();
                JOptionPane.showMessageDialog(null, "Success !! Request is assigned to you ");
            } else {
                JOptionPane.showMessageDialog(null, "Can't assign this work request, as the work request is in " + req.getReqStatus() + " status", "Warning!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }
    private void btnProcessReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessReqActionPerformed
        // TODO add your handling code here:
        int slRow = tblWrkReqTbl.getSelectedRow();
        if (slRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first from the table to view details");
            return;
        } else {

            GovFundReq request = (GovFundReq) tblWrkReqTbl.getValueAt(slRow, 0);

            if (request.getReqStatus().equals("Rejected")) {
                JOptionPane.showMessageDialog(null, "Cannot process a Rejected Request", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (request.getReqStatus().equalsIgnoreCase("Sent to Secretary")) {
                JOptionPane.showMessageDialog(null, "Request already processed", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (request.getReqStatus().equalsIgnoreCase("Sent")) {
                JOptionPane.showMessageDialog(null, "Assign the request first");
                return;
            }
            if (!usrAcnt.equals(request.getRcvr())) {
                JOptionPane.showMessageDialog(null, "Not Authorized", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (!usrAcnt.getEmploye().equals(request.getRcvr().getEmploye())) {
                JOptionPane.showMessageDialog(null, "Request assigned to other Officer", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            } else {

                OfficerProcessWorkRequestJPanel panel = new OfficerProcessWorkRequestJPanel(jPanel, usrAcnt, request, entrpz);
                jPanel.add("OfficerProcessWorkRequestJPanel", panel);
                CardLayout layout = (CardLayout) jPanel.getLayout();
                layout.next(jPanel);

            }
    }//GEN-LAST:event_btnProcessReqActionPerformed
    }
    private void btnVrcfnOnMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVrcfnOnMapActionPerformed
        // TODO add your handling code here:
        MapJPanel mapJPanel = new MapJPanel(jPanel);
        jPanel.add("mapJPanel",mapJPanel);
        CardLayout layout=(CardLayout)jPanel.getLayout();
        layout.next(jPanel);

    }//GEN-LAST:event_btnVrcfnOnMapActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnProcessReq;
    private javax.swing.JButton btnVrcfnOnMap;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGovHealthOfcrWrkArea;
    private javax.swing.JTable tblWrkReqTbl;
    // End of variables declaration//GEN-END:variables

    public void pplTbl() {
        DefaultTableModel model = (DefaultTableModel) tblWrkReqTbl.getModel();

        model.setRowCount(0);

        for (WorkReq req : hlthCrOfcrJPanel.getWrkQ().getWrkReqs()) {
            Object[] row = new Object[5];
            String status = req.getReqStatus();
            row[0] = ((GovFundReq) req);
            row[1] = req.getSndr().getEmploye().getEmpName();
            if (status.equalsIgnoreCase("Sent to Treasurer") || status.equalsIgnoreCase("Sent to Secretary")) {
                row[2] = null;
            } else {
                row[2] = req.getRcvr() == null ? null : req.getRcvr().getEmploye().getEmpName();
            }
            row[3] = req.getReqStatus();
            row[4] = ((GovFundReq) req).getAmountRequested();

            model.addRow(row);
        }
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblWrkReqTbl.setRowSorter(sorter);
    }
}
