/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InsuranceFinanceRole;

import Business.Enterprise.Enterprise;
import Business.SystemUserAccount.SystemUsers;
import Business.WorkQueue.InsReq;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Parth
 */
public class InsuranceFinanceProcessRequest extends javax.swing.JPanel {

    private JPanel jPanel;
    private Enterprise entrpz;
    private SystemUsers usrAcnt;
    private InsReq isnrWrReq;

    /**
     * Creates new form InsuranceFinanceProcessRequest
     */
    InsuranceFinanceProcessRequest(JPanel userProcessContainer, SystemUsers userAccount, InsReq insuranceWorkRequest, Enterprise enterprise) {
        initComponents();
        this.jPanel = userProcessContainer;
        this.entrpz = enterprise;
        this.usrAcnt = userAccount;
        this.isnrWrReq = insuranceWorkRequest;
        txtPlcyo.setText(insuranceWorkRequest.getPolicyNumber());
        txtSSN.setText(insuranceWorkRequest.getSocialsecurityNumber());
        txtPlcyNm.setText(insuranceWorkRequest.getNameOfPolicy());
        txtClmAmt.setText(String.valueOf(insuranceWorkRequest.getClmAmt()));
        txtBllngAmt.setText(String.valueOf(insuranceWorkRequest.getBillingAmt()));
        txtCoverage.setText(String.valueOf(insuranceWorkRequest.getInsuranceCust().getIns().getCoverage()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDsbrsAmt = new javax.swing.JButton();
        btnReqClm = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        lblPlcyNo = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtPlcyo = new javax.swing.JTextField();
        txtPlcyNm = new javax.swing.JTextField();
        lblPlcym = new javax.swing.JLabel();
        txtBllngAmt = new javax.swing.JTextField();
        mt = new javax.swing.JLabel();
        txtClmAmt = new javax.swing.JTextField();
        lblClmAmt = new javax.swing.JLabel();
        lblSsn = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblCoverage = new javax.swing.JLabel();
        txtCoverage = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(null);

        btnDsbrsAmt.setBackground(new java.awt.Color(0, 102, 102));
        btnDsbrsAmt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDsbrsAmt.setForeground(new java.awt.Color(255, 255, 255));
        btnDsbrsAmt.setText("Disburse Amount");
        btnDsbrsAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDsbrsAmtActionPerformed(evt);
            }
        });
        add(btnDsbrsAmt);
        btnDsbrsAmt.setBounds(110, 340, 141, 32);

        btnReqClm.setBackground(new java.awt.Color(0, 102, 102));
        btnReqClm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnReqClm.setForeground(new java.awt.Color(255, 255, 255));
        btnReqClm.setText("Reject Claim");
        btnReqClm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqClmActionPerformed(evt);
            }
        });
        add(btnReqClm);
        btnReqClm.setBounds(290, 340, 114, 32);

        lblHeading.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblHeading.setText("Insurance Finance Request Process area ");
        add(lblHeading);
        lblHeading.setBounds(130, 17, 420, 29);

        lblPlcyNo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlcyNo.setText("Policy Number");
        add(lblPlcyNo);
        lblPlcyNo.setBounds(150, 90, 89, 17);

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(10, 23, 63, 29);

        txtPlcyo.setEditable(false);
        add(txtPlcyo);
        txtPlcyo.setBounds(278, 86, 116, 23);

        txtPlcyNm.setEditable(false);
        add(txtPlcyNm);
        txtPlcyNm.setBounds(278, 209, 116, 23);

        lblPlcym.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlcym.setText("Policy Name");
        add(lblPlcym);
        lblPlcym.setBounds(160, 210, 90, 17);

        txtBllngAmt.setEditable(false);
        txtBllngAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBllngAmtActionPerformed(evt);
            }
        });
        add(txtBllngAmt);
        txtBllngAmt.setBounds(278, 247, 116, 23);

        mt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mt.setText("Billing Amount");
        add(mt);
        mt.setBounds(140, 250, 110, 17);

        txtClmAmt.setEditable(false);
        txtClmAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClmAmtActionPerformed(evt);
            }
        });
        add(txtClmAmt);
        txtClmAmt.setBounds(278, 285, 116, 23);

        lblClmAmt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblClmAmt.setText("Claim Amount");
        add(lblClmAmt);
        lblClmAmt.setBounds(140, 290, 100, 17);

        lblSsn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSsn.setText("SSN");
        add(lblSsn);
        lblSsn.setBounds(210, 130, 50, 17);

        txtSSN.setEditable(false);
        add(txtSSN);
        txtSSN.setBounds(278, 124, 116, 23);

        lblCoverage.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCoverage.setText("Coverage%");
        add(lblCoverage);
        lblCoverage.setBounds(170, 177, 73, 20);

        txtCoverage.setEditable(false);
        add(txtCoverage);
        txtCoverage.setBounds(278, 171, 116, 23);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insurance finance request.gif"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel2);
        jLabel2.setBounds(-40, 10, 790, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDsbrsAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDsbrsAmtActionPerformed

        btnDsbrsAmt.setEnabled(true);
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
        if (dialogResult == JOptionPane.YES_OPTION) {
            isnrWrReq.setReqStatus("Insurance Claim Approved");
            JOptionPane.showMessageDialog(null, "Claim Approved Successfully!!!");
            btnDsbrsAmt.setEnabled(false);
            btnReqClm.setEnabled(false);
        }
    }//GEN-LAST:event_btnDsbrsAmtActionPerformed

    private void btnReqClmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqClmActionPerformed

        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
        if (dialogResult == JOptionPane.YES_OPTION) {
            isnrWrReq.setReqStatus("Insurance Claim Rejected");
            btnReqClm.setEnabled(false);
            btnDsbrsAmt.setEnabled(false);
        }

    }//GEN-LAST:event_btnReqClmActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        jPanel.remove(this);
        Component[] componentArray = jPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        InsuranceFinanceWorkAreaJPanel iwjp = (InsuranceFinanceWorkAreaJPanel) component;
        iwjp.pplTabl();
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtClmAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClmAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClmAmtActionPerformed

    private void txtBllngAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBllngAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBllngAmtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDsbrsAmt;
    private javax.swing.JButton btnReqClm;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblClmAmt;
    private javax.swing.JLabel lblCoverage;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblPlcyNo;
    private javax.swing.JLabel lblPlcym;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel mt;
    private javax.swing.JTextField txtBllngAmt;
    private javax.swing.JTextField txtClmAmt;
    private javax.swing.JTextField txtCoverage;
    private javax.swing.JTextField txtPlcyNm;
    private javax.swing.JTextField txtPlcyo;
    private javax.swing.JTextField txtSSN;
    // End of variables declaration//GEN-END:variables
}
