/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InsuranceFinanceRole;

import Business.Enterprise.Enterprise;
import Business.Org.OrgInsuranceFinance;
import Business.SystemUserAccount.SystemUsers;
import Business.WorkQueue.InsReq;
import Business.WorkQueue.WorkReq;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Parth
 */
public class InsuranceFinanceWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel jPanel;
    
    private SystemUsers usrAcnt;
    private OrgInsuranceFinance insrFincOrg;
    private Enterprise entrpz;

    /**
     * Creates new form InsuranceFinanceWorkAreaJPanel
     */
    public InsuranceFinanceWorkAreaJPanel(JPanel userProcessContainer, SystemUsers account, OrgInsuranceFinance insuranceFinanceOrganization, Enterprise enterprise) {
        initComponents();
        this.jPanel = userProcessContainer;
        this.usrAcnt = account;
        this.insrFincOrg = insuranceFinanceOrganization;
        this.entrpz = enterprise;
        pplTabl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInsFinance = new javax.swing.JTable();
        btnAssgndToMe = new javax.swing.JButton();
        btnPrcsReq = new javax.swing.JButton();
        img = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Insurance Finance Work Area");

        tblInsFinance.setBackground(new java.awt.Color(204, 204, 204));
        tblInsFinance.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tblInsFinance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Policy Number", "Policy Name", "Coverage%", "Claim Amount", "Bill Amount", "Insurance Claim Status", "Requesting HealthCenter ", "Finance Manager"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInsFinance);

        btnAssgndToMe.setBackground(new java.awt.Color(0, 102, 102));
        btnAssgndToMe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAssgndToMe.setForeground(new java.awt.Color(255, 255, 255));
        btnAssgndToMe.setText("Assign To Me");
        btnAssgndToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssgndToMeActionPerformed(evt);
            }
        });

        btnPrcsReq.setBackground(new java.awt.Color(0, 102, 102));
        btnPrcsReq.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPrcsReq.setForeground(new java.awt.Color(255, 255, 255));
        btnPrcsReq.setText("Process Request");
        btnPrcsReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrcsReqActionPerformed(evt);
            }
        });

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insurance agent.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(btnAssgndToMe)
                        .addGap(57, 57, 57)
                        .addComponent(btnPrcsReq))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssgndToMe)
                    .addComponent(btnPrcsReq))
                .addGap(16, 16, 16)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(379, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssgndToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssgndToMeActionPerformed
        int selectedRow = tblInsFinance.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first from the table to view details");
            return;
        } else {
            WorkReq req = (InsReq) tblInsFinance.getValueAt(selectedRow, 0);
            if (req.getReqStatus().equals("Sent To Finance Department")) {
                req.setRcvr(usrAcnt);
                req.setReqStatus("Pending on " + req.getRcvr().getEmploye().getEmpName());
                pplTabl();
                JOptionPane.showMessageDialog(null, "Success !! Request is assigned to you");
            } else {
                JOptionPane.showMessageDialog(null, "Can't assign this work request, as the work request is in " + req.getReqStatus() + " status", "Warning!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAssgndToMeActionPerformed

    private void btnPrcsReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrcsReqActionPerformed
        // TODO add your handling code here:
        int selRow = tblInsFinance.getSelectedRow();
        if (selRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first from the table to view details");
            return;
        } else {

            InsReq insrWrReq = (InsReq) tblInsFinance.getValueAt(selRow, 0);
            if (insrWrReq.getReqStatus().equalsIgnoreCase("Sent To Finance Department")) {
                JOptionPane.showMessageDialog(null, "Assign the request first");
                return;
            }
            if (insrWrReq.getReqStatus().equalsIgnoreCase("Insurance Claim Approved")) {
                JOptionPane.showMessageDialog(null, "Request already Completed", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (!usrAcnt.equals(insrWrReq.getRcvr())) {
                JOptionPane.showMessageDialog(null, "Not Authorized", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (!usrAcnt.getEmploye().equals(insrWrReq.getRcvr().getEmploye())) {
                JOptionPane.showMessageDialog(null, "Request assigned to other Officer", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (insrWrReq.getReqStatus().equals("Insurance Claim Rejected")) {
                JOptionPane.showMessageDialog(null, "Cannot process a Rejected Request", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            } else {

                InsuranceFinanceProcessRequest panel = new InsuranceFinanceProcessRequest(jPanel, usrAcnt, insrWrReq, entrpz);
                jPanel.add("OfficerProcessWorkRequestJPanel", panel);
                CardLayout layout = (CardLayout) jPanel.getLayout();
                layout.next(jPanel);

            }
        }
    }//GEN-LAST:event_btnPrcsReqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssgndToMe;
    private javax.swing.JButton btnPrcsReq;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInsFinance;
    // End of variables declaration//GEN-END:variables

    public void pplTabl() {

        DefaultTableModel model = (DefaultTableModel) tblInsFinance.getModel();
        model.setRowCount(0);

        for (WorkReq workRequest : insrFincOrg.getWrkQ().getWrkReqs()) {
            InsReq insrWkReq = ((InsReq) workRequest);
            Object[] row = new Object[8];
            row[0] = insrWkReq;
            row[1] = insrWkReq.getNameOfPolicy();
            row[2] = insrWkReq.getInsuranceCust().getIns().getCoverage();
            row[3] = insrWkReq.getClmAmt();
            row[4] = insrWkReq.getBillingAmt();
            row[5] = insrWkReq.getReqStatus();
            row[6] = insrWkReq.getInsuranceName();
            row[7] = insrWkReq.getRcvr() == null ? "" : insrWkReq.getRcvr().getEmploye().getEmpName();

            model.addRow(row);
        }
        
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblInsFinance.setRowSorter(sorter);
    }

}
